version: '3.7'

# docker build --no-cache
# docker-compose up -d
# docker ps

services:
  backend:
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongo
    build:
      dockerfile: ./docker/.docker/node/Dockerfile
      context: ./backend
    ports:
      - '8080:8080'
    networks:
      - app-network
    environment:
      - clientID="${clientID}"
      - clientSecret="${clientSecret}"
      - secret="${secret}"
      - origin="${origin}"
      - dbURI="${dbURI}"

  client:
    container_name: client
    restart: unless-stopped
    depends_on:
      - backend
    build:
      dockerfile: ./.docker/.docker/client/Dockerfile
      context: ./client
    ports:
      - '3000:3000'
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017

  redis:
    image: redis:alpine
    command: redis-cli -h redis
    volumes:
      - ./data:/data
  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 8001:8001

 networks:
  app-network:
    driver: bridge

 volumes:
  mongodbdata:
  node_modules:
  web-root:
    driver: local
